### ISSUE TITLE
`archlinux` broken on armv7 with overwritten pacman.conf

### ISSUE THREAD

**Issue by jclds139** [heywoodlh/dockerfiles#4]
When you're making the combined `heywoodlh/archlinux` image you're overwriting `pacman.conf`. It's not a problem for the 64-bit arm builds, but you're then overwriting the `Arch` option for 32-bit builds, which breaks the image. The base `archlinuxarm` image seems fine, just don't overwrite pacman.conf for the combined manifest.

**Comment by heywoodlh** [comment]
Whoa, thanks for this catch! It slipped through because I don't really use any 32 bit ARM systems anymore so I didn't do any testing.

I just tested and it seems to be working with this commit: 01e78d5cafd4e5e050428aa5eb4493bf484ea7e0

Can you pull the latest `heywoodlh/archlinux:latest` and see if you still have issues with it?

**Comment by jclds139** [comment]
It looks good now, thanks!

Jesse Codling

**Comment by jclds139** [comment]
It's working now, thanks!
